# http://wiki.ros.org/actionlib_tutorials/Tutorials/SimpleActionServer%28GoalCallbackMethod%29
# goal definition
float64[3] target
float64 speed
---
# result definition
int32 succes
---
# feedback
float64[3] velocity